# ===================================
#  List Behavior Config
# ===================================

title: nitm.api::lang.eventlogs.page_title
list: ~/plugins/nitm/api/models/eventlog/columns.yaml
modelClass: Nitm\Api\Models\Eventlog
recordUrl: nitm/api/eventhistory/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
