# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: nitm.api::lang.blacklist.page_title

# Model Form Field configuration
form: ~/plugins/nitm/api/models/logs/fields.yaml

# Model Class name
modelClass: Nitm\Api\Models\Logs

# Default redirect location
defaultRedirect: nitm/api/history

# Preview page
preview:
    title: nitm.api::lang.logs.details
