# ===================================
#  List Behavior Config
# ===================================

title: Event Handler
list: ~/plugins/nitm/api/models/eventhandler/columns.yaml
modelClass: Nitm\Api\Models\Eventhandler
recordUrl: nitm/api/eventhandler/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showCheckboxes: yes
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
