fields:
  api_status:
    span: left
    type: switch
    label: nitm.api::lang.settings.api_status.title
    commentAbove: nitm.api::lang.settings.api_status.desc

  direct_table_output:
    span: right
    type: switch
    label: nitm.api::lang.settings.direct_table_output.title
    commentAbove: nitm.api::lang.settings.direct_table_output.desc

  api_logs:
    span: left
    type: switch
    label: nitm.api::lang.settings.api_logs.title
    commentAbove: nitm.api::lang.settings.api_logs.desc

tabs:
  fields:
    admin_key:
      tab: nitm.api::lang.settings.specific
      span: left
      label: nitm.api::lang.settings.admin_key.title
      commentAbove: nitm.api::lang.settings.admin_key.desc
      default: your_secret_admin_key_change_me

    output_style:
      tab: nitm.api::lang.settings.specific
      span: right
      type: dropdown
      label: nitm.api::lang.settings.output_style.title
      commentAbove: nitm.api::lang.settings.output_style.desc

    auth_with_user:
      tab: nitm.api::lang.settings.specific
      span: left
      type: switch
      label: nitm.api::lang.settings.auth_with_user.title
      commentAbove: nitm.api::lang.settings.auth_with_user.desc

    charsets:
      tab: nitm.api::lang.settings.specific
      span: right
      type: dropdown
      label: nitm.api::lang.settings.charsets.title
      commentAbove: nitm.api::lang.settings.charsets.desc

    external_keys:
      tab: nitm.api::lang.settings.additional
      span: left
      type: textarea
      size: large
      label: nitm.api::lang.settings.external_keys.title
      commentAbove: nitm.api::lang.settings.external_keys.desc

    json_flag:
      tab: nitm.api::lang.settings.additional
      span: right
      type: switch
      label: nitm.api::lang.settings.json_flag.title
      commentAbove: nitm.api::lang.settings.json_flag.desc

    xml_cdata:
      tab: nitm.api::lang.settings.additional
      span: right
      type: switch
      label: nitm.api::lang.settings.xml_cdata.title
      commentAbove: nitm.api::lang.settings.xml_cdata.desc

    purge_logs_after:
      tab: nitm.api::lang.settings.logs_settings
      span: left
      type: number
      label: nitm.api::lang.settings.purge_logs_after.title
      commentAbove: nitm.api::lang.settings.purge_logs_after.desc
      default: 0

    time_now:
      tab: nitm.api::lang.settings.schedule
      span: left
      type: partial
      path: ~/plugins/nitm/api/models/configs/_field_time_now.htm
      label: nitm.api::lang.settings.time_now.title
      comment: nitm.api::lang.settings.time_now.desc

    timezone:
      tab: nitm.api::lang.settings.schedule
      span: right
      type: dropdown
      label: nitm.api::lang.settings.timezone.title
      comment: nitm.api::lang.settings.timezone.desc

    schedule_status:
      tab: nitm.api::lang.settings.schedule
      label: nitm.api::lang.settings.schedule_status.title
      comment: nitm.api::lang.settings.schedule_status.desc
      type: checkbox

    api_schedule_start:
      tab: nitm.api::lang.settings.schedule
      span: left
      type: datepicker
      label: nitm.api::lang.settings.api_schedule_start.title
      commentAbove: nitm.api::lang.settings.api_schedule_start.desc
      cssClass: field-indent
      trigger:
        action: show
        field: schedule_status
        condition: checked

    api_schedule_end:
      tab: nitm.api::lang.settings.schedule
      span: right
      type: datepicker
      label: nitm.api::lang.settings.api_schedule_end.title
      commentAbove: nitm.api::lang.settings.api_schedule_end.desc
      cssClass: field-indent
      trigger:
        action: show
        field: schedule_status
        condition: checked

    ip_blacklist:
      tab: nitm.api::lang.settings.blacklist
      span: left
      type: textarea
      size: large
      label: nitm.api::lang.settings.ip_blacklist.title
      commentAbove: nitm.api::lang.settings.ip_blacklist.desc
    tokens_duration:
      tab: nitm.api::lang.settings.tokens.title
      span: left
      type: number
      label: nitm.api::lang.settings.tokens.duration
      commentAbove: nitm.api::lang.settings.tokens.desc
