# ===================================
#  List Behavior Config
# ===================================

title: nitm.api::lang.tokens.page_title
list: ~/plugins/nitm/api/models/token/columns.yaml
modelClass: Nitm\Api\Models\Token
recordUrl: nitm/api/tokens/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
