# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: nitm.api::lang.token.page_title_one

# Model Form Field configuration
form: ~/plugins/nitm/api/models/token/fields.yaml

# Model Class name
modelClass: Nitm\Api\Models\Token

# Default redirect location
defaultRedirect: nitm/api/tokens

# Preview page
preview:
    title: nitm.api::lang.token.details
